server:
  port: 8077
spring:
  jpa:
#    properties:
#      hibernate:
#        format_sql: true
#    #配置在日志中打印出执行的 SQL 语句信息。
#    show-sql: false

    open-in-view: false #view层的session缓存开关
    hibernate:
#      show_sql: false
      #ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  main:
    allow-bean-definition-overriding: true

#MsDataSource
ms-datasource:
    # 多数据源开启
    enabled: true
    # 多账套开启:false则读取master/slave,true则仅读取main
    suit-enabled: true
    # 日志开关
    log.enabled: false
    # 驼峰命名
    implicit-naming: true
    # 缺省数据源
    suit-default-ds-name: MASTER
    # 策略自动读写分离
    strategy: NORMAL_RW # NORMAL_RW TX_WRITE_FIRST
    # 数据源以druid格式加载
    type: com.alibaba.druid.pool.DruidDataSource
    # 是否使用缺省产品识别模式
    product-default-mode: true
    # 缺省产品识别模式使用http头哪个字段
    product-default-mode-http-header-pd-field: pkgName
    main:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://127.0.0.1:3306/api_main?useUnicode=true&allowMultiQueries=true&useSSL=false&characterEncoding=UTF-8
      username: root
      password:
      # 初始化连接大小
      initial-size: 1
      # 最小空闲连接数
      min-idle: 1
      max-active: 20
      max-wait: 30000

    master:
#      driver-class-name: com.mysql.jdbc.Driver
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password:
      # 初始化连接大小
      initial-size: 1
      # 最小空闲连接数
      min-idle: 1
      max-active: 20
      max-wait: 30000
      # 可关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters
      filters: stat
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
    slave:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: test_reader
      password: test_reader
      # 初始化连接大小
      initial-size: 1
      # 最小空闲连接数
      min-idle: 1
      max-active: 20
      max-wait: 30000
      # 可关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters
      filters: stat
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"